config/routes.rb
Rails.application.routes.draw do
  devise_for :managers, controllers: { omniauth_callbacks: 'managers/omniauth_callbacks' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete "users/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  devise_scope :manager do
    delete "managers/sign_out", to: "devise/sessions#destroy", as: :destroy_manager_session
  end

  root to: "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: %i[manager_facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: %i[user_facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/managers/omniauth_callbacks_controller.rb
class Managers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def manager_facebook
    @manager = Manager.from_omniauth(request.env["omniauth.auth"])

    if @manager.persisted?
      sign_in_and_redirect @manager, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def user_facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<h1>User auth info</h1>
<%- if current_user.present? %>
  <div><%= "Signed in User: #{current_user.name}" %></div>
  <div><%= link_to 'Sign out User', destroy_user_session_path, method: :delete %></div>
<% else %>
  <div>User is signed out</div>
  <div><%= link_to "Sign in User with Facebook", user_user_facebook_omniauth_authorize_path %></div>
<% end %>

<h1>Manager auth info</h1>
<%- if current_manager.present? %>
  <div><%= "Signed in Manager: #{current_manager.name}" %></div>
  <div><%= link_to 'Sign out Manager', destroy_manager_session_path, method: :delete %></div>
<% else %>
  <div>Manager is signed out</div>
  <div><%= link_to "Sign in Manager with Facebook", manager_manager_facebook_omniauth_authorize_path %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultipleOmniauthModels</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>